# This is free software, licensed under the Apache License, Version 2.0
#
# Copyright (C) 2024 Maizil <maizilpc7@gmail.com>

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI For Access Management.
LUCI_DEPENDS:=+luci
LUCI_DESCRIPTION:=Bot Whatsapp for Radius Monitor.
LUCI_MAINTAINER:=Maizil41 <https://github.com/Maizil41>

PKG_MAINTAINER:=TaufikNRA <https://github.com/TaufikNRA>
PKG_VERSION:=1.0
PKG_RELEASE:=1
PKG_LICENSE:=Apache-2.0
PKG_ARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
