#!/bin/sh /etc/rc.common

START=60

BASH_FILE="/usr/bin/access-management"

start() {
    "$BASH_FILE" start 2>&1 &
}

stop() {
    "$BASH_FILE" stop 2>&1 &
}

restart() {
    "$BASH_FILE" restart 2>&1 &
}

reload() {
    "$BASH_FILE" restart 2>&1 &
}